package com.gokcank.valutarate.presentation.localization

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String) {
    TR("tr", "Türkçe"),
    EN("en", "English"),
    DE("de", "Deutsch"),
    FR("fr", "Français")
}

data class AppStrings(
    val languageCode: String,
    val appName: String = "Valuta Rate",
    val tabHome: String,
    val tabConvert: String,
    val tabSettings: String,
    val amount: String,
    val from: String,
    val to: String,
    val usingTcmbOfficial: String,
    val usingGlobalLive: String,
    val convertedAmount: String,
    val tcmbRatesHeader: String,
    val errorLoading: String,
    val themePalette: String,
    val language: String,
    val dataSources: String,
    val tcmbTitle: String = "TCMB",
    val tcmbDescription: String,
    val about: String,
    val developer: String,
    val reportBug: String,
    val bugReportSubject: String,
    val appVersionLabel: String,
    val buying: String,
    val selling: String,
    val tabFavorites: String,
    val tabAll: String,
    val privacyPolicy: String,
    val offlinePrefix: String,
    val timeUntilUpdate: String,
    val shareTitle: String,
    val isEqualTo: String
)

val enStrings = AppStrings(
    languageCode = "en",
    tabHome = "Home",
    tabConvert = "Convert",
    tabSettings = "Settings",
    usingTcmbOfficial = "Using TCMB Official Cross Rates",
    usingGlobalLive = "Using Global Live Rates",
    amount = "Amount",
    from = "From",
    to = "To",
    convertedAmount = "Converted Amount",
    dataSources = "Data Sources",
    tcmbTitle = "TCMB (Central Bank of the Republic of Turkey)",
    tcmbDescription = "Provides official indicative exchange rates for the Turkish Lira. Rates are updated every business day at 15:30.",
    themePalette = "Theme Palette",
    language = "Language",
    about = "About",
    developer = "Developer",
    tcmbRatesHeader = "Indicative TCMB Rates determined at 15:30 on {date}",
    errorLoading = "Error loading data",
    reportBug = "Report Bug",
    bugReportSubject = "VALUTA RATE BUG REPORT",
    appVersionLabel = "Valuta Rate v1.2.0",
    buying = "Buy",
    selling = "Sell",
    tabFavorites = "Favorites",
    tabAll = "All",
    privacyPolicy = "Privacy Policy",
    offlinePrefix = "Offline - ",
    timeUntilUpdate = "Time until update: ",
    shareTitle = "Share Exchange Rates",
    isEqualTo = "is equal to:"
)

val trStrings = AppStrings(
    languageCode = "tr",
    tabHome = "Ana Sayfa",
    tabConvert = "Çevirici",
    tabSettings = "Ayarlar",
    usingTcmbOfficial = "TCMB Gösterge Kurları Kullanılıyor",
    usingGlobalLive = "Küresel Canlı Kurlar Kullanılıyor",
    amount = "Miktar",
    from = "Nereden",
    to = "Nereye",
    convertedAmount = "Çevrilen Tutar",
    dataSources = "Veri Kaynakları",
    tcmbTitle = "TCMB (Türkiye Cumhuriyet Merkez Bankası)",
    tcmbDescription = "Türk Lirası için resmi gösterge kurlarını sağlar. Kurlar her iş günü saat 15:30'da güncellenir.",
    themePalette = "Tema Paleti",
    language = "Dil",
    about = "Hakkında",
    developer = "Geliştirici",
    tcmbRatesHeader = "{date} Tarihinde Saat 15:30'da Belirlenen Gösterge Niteliğindeki TCMB Kurları",
    errorLoading = "Kurlar yüklenirken hata oluştu",
    reportBug = "Hata Bildir",
    bugReportSubject = "DÖVİZ ÇEVİRİCİ - VALUTA RATE HATA BİLDİRİMİ",
    appVersionLabel = "Döviz Çevirici - Valuta Rate v1.2.0",
    buying = "Alış",
    selling = "Satış",
    tabFavorites = "Favoriler",
    tabAll = "Tümü",
    privacyPolicy = "Gizlilik Politikası",
    offlinePrefix = "Çevrimdışı - ",
    timeUntilUpdate = "Güncellemeye Kalan: ",
    shareTitle = "Kurları Paylaş",
    isEqualTo = "eşittir:"
)

val deStrings = AppStrings(
    languageCode = "de",
    tabHome = "Startseite",
    tabConvert = "Umrechner",
    tabSettings = "Einstellungen",
    usingTcmbOfficial = "TCMB Offizielle Kreuzkurse werden verwendet",
    usingGlobalLive = "Globale Live-Kurse werden verwendet",
    amount = "Betrag",
    from = "Von",
    to = "Nach",
    convertedAmount = "Umgerechneter Betrag",
    dataSources = "Datenquellen",
    tcmbTitle = "TCMB (Zentralbank der Republik Türkei)",
    tcmbDescription = "Stellt offizielle indikative Wechselkurse für die türkische Lira bereit. Die Kurse werden jeden Werktag um 15:30 Uhr aktualisiert.",
    themePalette = "Farbpalette",
    language = "Sprache",
    about = "Über",
    developer = "Entwickler",
    tcmbRatesHeader = "Indikative TCMB-Kurse, ermittelt um 15:30 Uhr am {date}",
    errorLoading = "Fehler beim Laden der Kurse",
    reportBug = "Fehler Melden",
    bugReportSubject = "VALUTA RATE FEHLERBERICHT",
    appVersionLabel = "Valuta Rate v1.2.0",
    buying = "Kauf",
    selling = "Verkauf",
    tabFavorites = "Favoriten",
    tabAll = "Alle",
    privacyPolicy = "Datenschutzerklärung",
    offlinePrefix = "Offline - ",
    timeUntilUpdate = "Zeit bis zum Update: ",
    shareTitle = "Wechselkurse teilen",
    isEqualTo = "entspricht:"
)

val frStrings = AppStrings(
    languageCode = "fr",
    tabHome = "Accueil",
    tabConvert = "Convertisseur",
    tabSettings = "Paramètres",
    usingTcmbOfficial = "Utilisation des taux croisés officiels de la TCMB",
    usingGlobalLive = "Utilisation des taux mondiaux en direct",
    amount = "Montant",
    from = "De",
    to = "À",
    convertedAmount = "Montant converti",
    dataSources = "Sources de données",
    tcmbTitle = "TCMB (Banque centrale de la République de Turquie)",
    tcmbDescription = "Fournit les taux de change indicatifs officiels pour la livre turque. Les taux sont mis à jour chaque jour ouvrable à 15h30.",
    themePalette = "Palette de thèmes",
    language = "Langue",
    about = "À propos",
    developer = "Développeur",
    tcmbRatesHeader = "Taux indicatifs de la TCMB déterminés à 15h30 le {date}",
    errorLoading = "Erreur de chargement des taux",
    reportBug = "Signaler un bug",
    bugReportSubject = "RAPPORT DE BUG VALUTA RATE",
    appVersionLabel = "Valuta Rate v1.2.0",
    buying = "Achat",
    selling = "Vente",
    tabFavorites = "Favoris",
    tabAll = "Tous",
    privacyPolicy = "Politique de confidentialité",
    offlinePrefix = "Hors ligne - ",
    timeUntilUpdate = "Temps avant la mise à jour : ",
    shareTitle = "Partager les taux de change",
    isEqualTo = "est égal à :"
)

val LocalAppStrings = staticCompositionLocalOf { enStrings }
